{
    'name': 'Labo Horizon — Laboratoire',
    'version': '20.0.1.11.0',
    'summary': "Patients, demandes d'analyses, résultats et comptes rendus",
    'category': 'Services',
    'author': 'OdooSkills',
    'website': 'https://odooskills.com',
    'license': 'LGPL-3',
    'depends': ['base', 'mail'],
    'data': [
        'security/lab_security.xml',
        'security/ir.access.csv',
        'data/ir_sequence_data.xml',
        'data/lab_analysis_data.xml',
        'data/lab_panel_data.xml',
        'data/lab_sequence_fix.xml',
        'views/lab_patient_views.xml',
        'views/lab_catalog_views.xml',
        'wizard/lab_result_entry_views.xml',
        'views/lab_request_views.xml',
        'data/lab_actions.xml',
        'views/lab_result_views.xml',
        'views/lab_menus.xml',
    ],
    'demo': ['demo/lab_demo.xml'],
    'application': True,
}
