{
    'name': 'Labo Horizon — Portail',
    'version': '20.0.1.21.0',
    'summary': 'Résultats validés en ligne, compte rendu en PDF, prise de rendez-vous sur le site, courriels',
    'category': 'Services',
    'author': 'OdooSkills',
    'website': 'https://odooskills.com',
    'license': 'LGPL-3',
    'depends': ['lab_billing', 'portal', 'website', 'calendar'],
    'data': [
        'security/ir.access.csv',
        'data/mail_template_data.xml',
        'data/ir_cron_data.xml',
        'data/portal_entry_data.xml',
        'data/lab_slot_data.xml',
        'data/website_menu_data.xml',
        'views/lab_patient_views.xml',
        'views/lab_portal_templates.xml',
        'views/lab_slot_views.xml',
        'views/calendar_event_views.xml',
        'views/lab_booking_templates.xml',
    ],
}
