{
    'name': 'Labo Horizon — Facturation',
    'version': '20.0.1.15.0',
    'summary': 'Patients reliés aux contacts, analyses reliées aux articles, mutuelles, factures patient et mutuelle',
    'category': 'Services',
    'author': 'OdooSkills',
    'website': 'https://odooskills.com',
    'license': 'LGPL-3',
    'depends': ['lab_core', 'account'],
    'data': [
        'security/lab_billing_security.xml',
        'security/ir.access.csv',
        'data/lab_analysis_price_data.xml',
        'views/lab_insurer_views.xml',
        'views/lab_patient_views.xml',
        'views/lab_analysis_views.xml',
        'views/res_partner_views.xml',
        'views/lab_request_views.xml',
        'views/account_move_views.xml',
        'data/lab_billing_actions.xml',
    ],
    'demo': ['demo/lab_billing_demo.xml'],
}
