from . import test_lab_patient
from . import test_lab_catalog
from . import test_lab_request
from . import test_lab_workflow
from . import test_lab_chatter
from . import test_lab_views
from . import test_lab_security
from . import test_lab_wizard
from . import test_lab_report
from . import test_lab_form
